before editorconfig
goosesnest/hellocsharp pull request #7
Opened 2020-12-01 04:34 UTC by kwacky1

This is my default PR Template

2021-02-10 02:21 UTC, lesleyanneb reviewed
Are you sure this will be good enough?

2021-02-10 02:22 UTC, lesleyanneb requested changes
I think this will be better

2021-02-10 02:22 UTC, lesleyanneb commented on bin/Debug/netcoreapp3.1/hellocsharp.deps.json
> +  "compilationOptions": {making a change for changes sake},
```suggestion
  "compilationOptions": {making a change for the future},
```

2021-02-10 03:25 UTC, kwacky1 commented
Thanks @lesleyanneb

2021-05-25 10:58 UTC, lesleyanneb approved these changes

2022-01-25 05:22 UTC, lesleyanneb commented
Can we close this PR or merge it

2022-01-25 05:28 UTC, merged